services:
  redis:
    image: redis:7.0-alpine
    command: "--port ${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/base-api-rails
    ports:
      - "${VIRTUAL_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - DOCKERIZED=true
      - LAUNCHY_DRY_RUN=true
      - BROWSER=/dev/null

networks:
  default:
    name: base-api-rails-network